os: osx
language: generic

# use oldest available image to be as compatible as possible when producing wheels
osx_image: xcode6.4 # = OS X 10.10 

env:
  global:
    #- LATEST_TAG=1
  matrix:
    # for each Python version the SciPy & scikit-image versions are chosen which are the oldest having a wheel available
    # this avoids errors like: "module compiled against API version 9 but this version of numpy is 7""
    - PYTHON_VERSION=2.7
      NUMPY_VERSION=1.7.1
      SCIPY_VERSION=0.13.0
      SKIMAGE_VERSION=0.10.1
      # (NumPy 1.7.2 has no macOS wheels)
            
    - PYTHON_VERSION=3.4
      NUMPY_VERSION=1.8.*
      SCIPY_VERSION=0.13.0
      SKIMAGE_VERSION=0.10.1
      
    - PYTHON_VERSION=3.5
      NUMPY_VERSION=1.9.*
      SCIPY_VERSION=0.16.1
      SKIMAGE_VERSION=0.12.3

    - PYTHON_VERSION=3.6
      NUMPY_VERSION=1.11.*
      SCIPY_VERSION=0.18.1
      SKIMAGE_VERSION=0.13.0

install:
  - cd terryfy && git fetch && git checkout master && cd ..
  - source terryfy/travis_tools.sh
  - travis_retry get_python_environment macports $PYTHON_VERSION venv
  - if [ -n "$LATEST_TAG" ]; then 
      checkout_closest_tag rawpy ;
    else
      cd rawpy ;
      git fetch ;
      git checkout -f master ;
      git log -n 1 ;
      cd .. ;
    fi
  - cd rawpy
  # necessary, otherwise the libraw submodule points to an old commit
  - git submodule update --recursive --init
  - travis_retry pip install numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION scikit-image==$SKIMAGE_VERSION
  - travis_retry pip install -r dev-requirements.txt
  - pip freeze
  - brew rm --ignore-dependencies jpeg
  - brew install jpeg
  - export CC=clang
  - export CXX=clang++
  - export CFLAGS="-arch x86_64"
  - export CXXFLAGS=$CFLAGS
  - export LDFLAGS=$CFLAGS
  - export ARCHFLAGS=$CFLAGS
  - python setup.py bdist_wheel
  - travis_retry pip install delocate
  - delocate-listdeps --all dist/*.whl # lists library dependencies
  - delocate-wheel --require-archs=x86_64 dist/*.whl # copies library dependencies into wheel
  - delocate-listdeps --all dist/*.whl # verify
  - pip install dist/*.whl
  - cd ..

script:
  # make sure it's working without any required libraries installed
  - brew rm --ignore-dependencies jpeg
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../rawpy/test
  - cd ..

deploy:
  provider: pypi
  user: letmaik
  skip_upload_docs: true
  skip_cleanup: true
  password:
    secure: "Gi+qCKpRNFjlvpOxBXjSNAq4yDhlSXfUUl9RZaOSdER+YURbc9/AMlfUuyOvpi09tAgwGnn9Hn3z7NqqjNV9auTcD30viMnevNbiyJaE2O/bw75FU9HqFmTM/OR7UVJp4sNtxtXy1Zp5CxmMnzRCjV3stQ9iaG9aJOV3sbUzDTQ="
  on:
    tags: true
